### ISSUE TITLE
Please add a screen shot & readme

### ISSUE THREAD

**Issue by unixorn** [emilHof/emilhoffish-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by emilHof** [comment]
hey @unixorn, 

thank you so much for reaching out about this! it is a quite shameless rip from the [agnoster](https://github.com/agnoster/agnoster-zsh-theme) theme, without really a direct attribution to it or it being a fork! it does not seem like they have a `LICENSE` file in their repo, and I was not too sure if it was under `CC` or something less restrictive...

considering this, would it still be alright to add something like this to your repo, once the `README` and screen shots and added ? would not want to get anyone upset or in trouble with this shameless rip-off hehe!

**Comment by unixorn** [comment]
Sure, once the readme and screen shots get added. I'll go file an issue on the upstream about the missing license.

**Comment by unixorn** [comment]
Given that the upstream's last commit was five years ago, I'll definitely add your plugin without waiting on them adding a license.

**Comment by emilHof** [comment]
bahaha! that is a very fair point! would it be alright if i renamed the repo and theme to be less... idio-referential?

**Comment by unixorn** [comment]
Sure. LMK when you're ready for it to be added by closing this issue

**Comment by emilHof** [comment]
okie, awesome, will do! thank you for doing me the honors hehe ! :D
